name: weather_api_client
description: Flutter package that handles weather API requests
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.4.0"
  flutter: "^3.22.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
