name: weather
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  location_api_client:
    path: packages/location_api_client
  meta: ^1.12.0
  weather_api_client:
    path: packages/weather_api_client
  weather_repository:
    path: packages/weather_repository

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
