name: weather_repository
description: Flutter package that handles Weather related requests
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  weather_api_client:
    path: ../weather_api_client

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
